[package]
name = "metrics"
edition = "2021"
version.workspace = true

[dependencies]
http = "1.4.0"
log = "0.4.29"
once_cell = "1.21.3"
parking_lot = "0.12.5"
rand = "0.8.5"

[dev-dependencies]
mock_instant = { version = "0.3.2" }
